#############################################################################
# Makefile for building: qtArmyCalc
# Generated by qmake (2.01a) (Qt 4.6.2) on: Thu Sep 15 01:58:14 2011
# Project:  qtArmyCalc.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -spec /usr/share/qt4/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile qtArmyCalc.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT_LIB -DQT_XML_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtXml -I/usr/include/qt4/QtWebKit -I/usr/include/qt4 -Ilibs/libmaia -Ilibs/quazip/quazip -I. -I.
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS)  -L/usr/lib libs/libmaia/libmaia.a libs/quazip/quazip/libquazip.a -lQtWebKit -lQtXml -lQtGui -lQtNetwork -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/main.cpp \
		src/mainwindow.cpp \
		src/dialogversioncheck.cpp moc_mainwindow.cpp \
		moc_dialogversioncheck.cpp \
		qrc_resources.cpp \
		qrc_dist.cpp
OBJECTS       = main.o \
		mainwindow.o \
		dialogversioncheck.o \
		moc_mainwindow.o \
		moc_dialogversioncheck.o \
		qrc_resources.o \
		qrc_dist.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		qtArmyCalc.pro
QMAKE_TARGET  = qtArmyCalc
DESTDIR       = 
TARGET        = qtArmyCalc

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h ui_dialogversioncheck.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: qtArmyCalc.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtWebKit.prl \
		/usr/lib/libQtXml.prl \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtNetwork.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile qtArmyCalc.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtWebKit.prl:
/usr/lib/libQtXml.prl:
/usr/lib/libQtGui.prl:
/usr/lib/libQtNetwork.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile qtArmyCalc.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/qtArmyCalc1.0.0 || $(MKDIR) .tmp/qtArmyCalc1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/qtArmyCalc1.0.0/ && $(COPY_FILE) --parents src/mainwindow.h src/dialogversioncheck.h .tmp/qtArmyCalc1.0.0/ && $(COPY_FILE) --parents icons/resources.qrc dist.qrc .tmp/qtArmyCalc1.0.0/ && $(COPY_FILE) --parents src/main.cpp src/mainwindow.cpp src/dialogversioncheck.cpp .tmp/qtArmyCalc1.0.0/ && $(COPY_FILE) --parents src/mainwindow.ui src/dialogversioncheck.ui .tmp/qtArmyCalc1.0.0/ && (cd `dirname .tmp/qtArmyCalc1.0.0` && $(TAR) qtArmyCalc1.0.0.tar qtArmyCalc1.0.0 && $(COMPRESS) qtArmyCalc1.0.0.tar) && $(MOVE) `dirname .tmp/qtArmyCalc1.0.0`/qtArmyCalc1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/qtArmyCalc1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp moc_dialogversioncheck.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_dialogversioncheck.cpp
moc_mainwindow.cpp: src/mainwindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/mainwindow.h -o moc_mainwindow.cpp

moc_dialogversioncheck.cpp: src/mainwindow.h \
		src/dialogversioncheck.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/dialogversioncheck.h -o moc_dialogversioncheck.cpp

compiler_rcc_make_all: qrc_resources.cpp qrc_dist.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_resources.cpp qrc_dist.cpp
qrc_resources.cpp: icons/resources.qrc \
		icons/print.png \
		icons/about.png \
		icons/new.png \
		icons/print_preview.png \
		icons/save_online.png \
		icons/save_all.png \
		icons/quit.png \
		icons/save.png \
		icons/folder.png \
		icons/online.png \
		icons/open.png \
		icons/revalidate.png
	/usr/bin/rcc -name resources icons/resources.qrc -o qrc_resources.cpp

qrc_dist.cpp: dist.qrc \
		engine.zip \
		twrs.zip
	/usr/bin/rcc -name dist dist.qrc -o qrc_dist.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_dialogversioncheck.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_dialogversioncheck.h
ui_mainwindow.h: src/mainwindow.ui
	/usr/bin/uic-qt4 src/mainwindow.ui -o ui_mainwindow.h

ui_dialogversioncheck.h: src/dialogversioncheck.ui
	/usr/bin/uic-qt4 src/dialogversioncheck.ui -o ui_dialogversioncheck.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

main.o: src/main.cpp src/mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o src/main.cpp

mainwindow.o: src/mainwindow.cpp src/mainwindow.h \
		ui_mainwindow.h \
		src/dialogversioncheck.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o src/mainwindow.cpp

dialogversioncheck.o: src/dialogversioncheck.cpp src/dialogversioncheck.h \
		src/mainwindow.h \
		ui_dialogversioncheck.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dialogversioncheck.o src/dialogversioncheck.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_dialogversioncheck.o: moc_dialogversioncheck.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_dialogversioncheck.o moc_dialogversioncheck.cpp

qrc_resources.o: qrc_resources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_resources.o qrc_resources.cpp

qrc_dist.o: qrc_dist.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_dist.o qrc_dist.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

